// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATATPkcw-QOplH1PW54X3Az5gSHSDnZ78',
    appId: '1:1059072486837:web:e7afb7a53c472ea7c3bdfc',
    messagingSenderId: '1059072486837',
    projectId: 'pirantibergerak',
    authDomain: 'pirantibergerak.firebaseapp.com',
    storageBucket: 'pirantibergerak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDdgR6esIS3GaFMQwAuS1FoB2vDSjt18',
    appId: '1:1059072486837:android:3cd3f510046abe18c3bdfc',
    messagingSenderId: '1059072486837',
    projectId: 'pirantibergerak',
    storageBucket: 'pirantibergerak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFucGjL8tLeoNyESstiV1vewNnzzalkng',
    appId: '1:1059072486837:ios:9e7c5d8f4961e879c3bdfc',
    messagingSenderId: '1059072486837',
    projectId: 'pirantibergerak',
    storageBucket: 'pirantibergerak.appspot.com',
    iosBundleId: 'com.example.pirantiBergerak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFucGjL8tLeoNyESstiV1vewNnzzalkng',
    appId: '1:1059072486837:ios:fbe742d6578bb7a7c3bdfc',
    messagingSenderId: '1059072486837',
    projectId: 'pirantibergerak',
    storageBucket: 'pirantibergerak.appspot.com',
    iosBundleId: 'com.example.pirantiBergerak.RunnerTests',
  );
}
